// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package elastic

import ()

var ()

// ClientMock is a mock implementation of Client.
//
//     func TestSomethingThatUsesClient(t *testing.T) {
//
//         // make and configure a mocked Client
//         mockedClient := &ClientMock{
//         }
//
//         // use mockedClient in code that requires Client
//         // and then make assertions.
//
//     }
type ClientMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
