// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package elastic

import ()

var ()

// SearchServiceMock is a mock implementation of SearchService.
//
//     func TestSomethingThatUsesSearchService(t *testing.T) {
//
//         // make and configure a mocked SearchService
//         mockedSearchService := &SearchServiceMock{
//         }
//
//         // use mockedSearchService in code that requires SearchService
//         // and then make assertions.
//
//     }
type SearchServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
