// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package http

import ()

var ()

// RequestMock is a mock implementation of Request.
//
//     func TestSomethingThatUsesRequest(t *testing.T) {
//
//         // make and configure a mocked Request
//         mockedRequest := &RequestMock{
//         }
//
//         // use mockedRequest in code that requires Request
//         // and then make assertions.
//
//     }
type RequestMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
