// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package http

import ()

var ()

// ResponseMock is a mock implementation of Response.
//
//     func TestSomethingThatUsesResponse(t *testing.T) {
//
//         // make and configure a mocked Response
//         mockedResponse := &ResponseMock{
//         }
//
//         // use mockedResponse in code that requires Response
//         // and then make assertions.
//
//     }
type ResponseMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
